# Generated by Django 5.0.1 on 2024-08-28 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envdata', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeByContracts',
            fields=[
                ('year', models.CharField(max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('county', models.CharField(choices=[('Arges', 'Arges'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Olt', 'Olt'), ('Mehedinti', 'Mehedinti'), ('Teleorman', 'Teleorman'), ('Valcea', 'Valcea')], max_length=255)),
                ('full_time_women', models.IntegerField()),
                ('full_time_men', models.IntegerField()),
                ('fixed_term_contract_women', models.IntegerField()),
                ('fixed_term_contract_men', models.IntegerField()),
                ('part_time_women', models.IntegerField()),
                ('part_time_men', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthAndSafety',
            fields=[
                ('year', models.CharField(max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=25)),
                ('total_working_hours', models.FloatField(max_length=25)),
                ('fatality_rate', models.FloatField(max_length=10)),
                ('high_consequence_rate', models.FloatField(max_length=10)),
                ('recordable_rate', models.FloatField(max_length=10)),
                ('ep_total_working_hours', models.FloatField(max_length=25)),
                ('ep_fatality_rate', models.FloatField(max_length=10)),
                ('ep_high_consequence_rate', models.FloatField(max_length=10)),
                ('ep_recordable_rate', models.FloatField(max_length=10)),
                ('total_training_hours', models.FloatField(max_length=25)),
                ('management_training_hours', models.FloatField(max_length=25)),
                ('operational_training_hours', models.FloatField(max_length=25)),
                ('women_management_training_hours', models.FloatField(max_length=25)),
                ('women_operational_training_hours', models.FloatField(max_length=25)),
                ('man_management_training_hours', models.FloatField(max_length=25)),
                ('man_operational_training_hours', models.FloatField(max_length=25)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewEmployeeByAge',
            fields=[
                ('year', models.CharField(max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('county', models.CharField(choices=[('Arges', 'Arges'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Olt', 'Olt'), ('Mehedinti', 'Mehedinti'), ('Teleorman', 'Teleorman'), ('Valcea', 'Valcea')], max_length=255)),
                ('men_under_30', models.IntegerField()),
                ('women_under_30', models.IntegerField()),
                ('men_between_30_and_50', models.IntegerField()),
                ('women_between_30_and_50', models.IntegerField()),
                ('men_over_50', models.IntegerField()),
                ('women_over_50', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetirementRate',
            fields=[
                ('year', models.CharField(max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('county', models.CharField(max_length=255)),
                ('retiring_next_10_years_management', models.IntegerField()),
                ('retiring_next_5_years_management', models.IntegerField()),
                ('retiring_next_10_years_operational', models.IntegerField()),
                ('retiring_next_5_years_operational', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RotationRateOfEmployeeByAge',
            fields=[
                ('year', models.CharField(max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('county', models.CharField(choices=[('Arges', 'Arges'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Olt', 'Olt'), ('Mehedinti', 'Mehedinti'), ('Teleorman', 'Teleorman'), ('Valcea', 'Valcea')], max_length=255)),
                ('men_under_30', models.IntegerField()),
                ('women_under_30', models.IntegerField()),
                ('men_between_30_and_50', models.IntegerField()),
                ('women_between_30_and_50', models.IntegerField()),
                ('men_over_50', models.IntegerField()),
                ('women_over_50', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
