# Generated by Django 5.0.1 on 2024-06-23 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envdata', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAndSafety',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')])),
                ('year', models.CharField(max_length=4)),
                ('total_working_hours', models.FloatField(max_length=25)),
                ('fatality_rate', models.FloatField(max_length=10)),
                ('high_consequence_rate', models.FloatField(max_length=10)),
                ('recordable_rate', models.FloatField(max_length=10)),
                ('ep_total_working_hours', models.FloatField(max_length=25)),
                ('ep_fatality_rate', models.FloatField(max_length=10)),
                ('ep_high_consequence_rate', models.FloatField(max_length=10)),
                ('ep_recordable_rate', models.FloatField(max_length=10)),
                ('total_training_hours', models.FloatField(max_length=25)),
                ('management_training_hours', models.FloatField(max_length=25)),
                ('operational_training_hours', models.FloatField(max_length=25)),
                ('women_management_training_hours', models.FloatField(max_length=25)),
                ('women_operational_training_hours', models.FloatField(max_length=25)),
                ('man_management_training_hours', models.FloatField(max_length=25)),
                ('man_operational_training_hours', models.FloatField(max_length=25)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
