# Generated by Django 5.0.1 on 2024-06-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthandsafety',
            name='external_provider_fatality_rate',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='external_provider_high_consequence_rate',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='external_provider_recordable_rate',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='external_provider_total_working_hours',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='man_management_training_hours',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='man_operational_training_hours',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='management_training_hours',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='operational_training_hours',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='own_fatality_rate',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='own_high_consequence_rate',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='own_recordable_rate',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='own_total_working_hours',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='total_training_hours',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='women_management_training_hours',
            field=models.FloatField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='healthandsafety',
            name='women_operational_training_hours',
            field=models.FloatField(default=0, max_length=25),
        ),
    ]
