# Generated by Django 5.0.1 on 2024-06-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebycontracts',
            name='fixed_term_contract_men',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeebycontracts',
            name='fixed_term_contract_women',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeebycontracts',
            name='full_time_men',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeebycontracts',
            name='full_time_women',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeebycontracts',
            name='part_time_men',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeebycontracts',
            name='part_time_women',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='retirementrate',
            name='retiring_next_10_years_management',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='retirementrate',
            name='retiring_next_10_years_operational',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='retirementrate',
            name='retiring_next_5_years_management',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='retirementrate',
            name='retiring_next_5_years_operational',
            field=models.IntegerField(),
        ),
    ]
