# Generated by Django 5.0.1 on 2024-07-05 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdata', '0002_alter_employeebycontracts_fixed_term_contract_men_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebycontracts',
            name='county',
            field=models.CharField(choices=[('Arges', 'Arges'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Olt', 'Olt'), ('Mehedinti', 'Mehedinti'), ('Teleorman', 'Teleorman'), ('Valcea', 'Valcea')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newemployeebyage',
            name='county',
            field=models.CharField(choices=[('Arges', 'Arges'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Olt', 'Olt'), ('Mehedinti', 'Mehedinti'), ('Teleorman', 'Teleorman'), ('Valcea', 'Valcea')]),
        ),
        migrations.AlterField(
            model_name='rotationrateofemployeebyage',
            name='county',
            field=models.CharField(choices=[('Arges', 'Arges'), ('Dolj', 'Dolj'), ('Gorj', 'Gorj'), ('Olt', 'Olt'), ('Mehedinti', 'Mehedinti'), ('Teleorman', 'Teleorman'), ('Valcea', 'Valcea')]),
        ),
    ]
