# Generated by Django 5.0.1 on 2024-02-25 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('measure_unit', models.CharField(max_length=20)),
                ('emission_factor', models.IntegerField(default=0, null=True)),
                ('calculation_method', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('fuel_type', models.CharField(choices=[('Diesel Fuel', 'Diesel '), ('Gasoline Fuel', 'Gasoline '), ('Biodiesel (100%) Fuel', 'Biodiesel'), ('Motor Gasoline Fuel', 'Motor Gasoline '), ('Ethanol (100%) Fuel', 'Ethanol '), ('Jet Fuel', 'Jet Fuel'), ('Aviation Fuel', 'Aviation Fuel'), ('Compressed Natural Gas', 'Compressed Natural Gas')], max_length=255)),
                ('fuel_source', models.CharField(max_length=255)),
                ('fuel_quantity', models.FloatField(default=0.0, max_length=10)),
                ('pollution_norm', models.CharField(choices=[('Euro 1', 'Euro 1'), ('Euro 2', 'Euro 2'), ('Euro 3', 'Euro 3'), ('Euro 4', 'Euro 4'), ('Euro 5', 'Euro 5'), ('Euro 6', 'Euro 6')], max_length=30)),
                ('activity_type', models.CharField(choices=[('Fuel use', 'Fuel use'), ('Distance Activity', 'Distance Activity'), ('Custom emission factor', 'Custom emission factor')], max_length=255)),
                ('vehicle_type', models.CharField(choices=[('Diesel passenger cars', 'Diesel passenger cars'), ('Diesel light-duty trucks', 'Diesel light-duty'), ('Diesel medium-and-heavy-trucks', 'Diesel medium-and-heavy-trucks'), ('Diesel agricultural equipment', 'Diesel agricultural equipment'), ('Diesel ships and boats', 'Diesel ships and boats'), ('Diesel medium-and-heavy-duty-Vehicles', 'Diesel-medium-and-heavy-Vehicles'), ('Other diesel Non-Road Vehicles', 'Other diesel Non-Road Vehicles')], max_length=255)),
                ('measure_unit', models.CharField(default='L', max_length=30)),
                ('emission_factor', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerant',
            fields=[
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('refrigerant_type', models.CharField(max_length=255)),
                ('refrigerant_quantity', models.FloatField(default=0.0, max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sf6',
            fields=[
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('equipment_type', models.CharField(max_length=255)),
                ('equipment_producer', models.CharField(max_length=255)),
                ('sf6_quantity', models.FloatField(max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('fuel_consumption', models.FloatField(default=7.5)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('waste_name', models.CharField(max_length=255)),
                ('quantity_recycled', models.FloatField()),
                ('quantity_disposed', models.FloatField()),
                ('quantity_land_filled', models.FloatField()),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
