# Generated by Django 5.0.1 on 2024-03-17 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')])),
                ('year', models.CharField(max_length=4)),
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('measure_unit', models.CharField(max_length=20)),
                ('energy_quantity', models.FloatField(default=0.0, max_length=20)),
                ('emission_factor', models.FloatField(default=0, null=True)),
                ('calculation_method', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')])),
                ('year', models.CharField(max_length=4)),
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('fuel_type', models.CharField(choices=[('Diesel Fuel', 'Diesel '), ('Gasoline Fuel', 'Gasoline '), ('Biodiesel (100%) Fuel', 'Biodiesel'), ('Motor Gasoline Fuel', 'Motor Gasoline '), ('Ethanol (100%) Fuel', 'Ethanol '), ('Jet Fuel', 'Jet Fuel'), ('Aviation Fuel', 'Aviation Fuel'), ('Compressed Natural Gas', 'Compressed Natural Gas')], max_length=255)),
                ('fuel_source', models.CharField(max_length=255)),
                ('fuel_quantity', models.FloatField(default=0.0, max_length=10)),
                ('pollution_norm', models.CharField(choices=[('Euro 1', 'Euro 1'), ('Euro 2', 'Euro 2'), ('Euro 3', 'Euro 3'), ('Euro 4', 'Euro 4'), ('Euro 5', 'Euro 5'), ('Euro 6', 'Euro 6')], max_length=30)),
                ('activity_type', models.CharField(choices=[('Fuel use', 'Fuel use'), ('Distance Activity', 'Distance Activity'), ('Custom emission factor', 'Custom emission factor')], max_length=255)),
                ('vehicle_type', models.CharField(choices=[('Diesel passenger cars', 'Diesel passenger cars'), ('Diesel light-duty trucks', 'Diesel light-duty'), ('Diesel medium-and-heavy-trucks', 'Diesel medium-and-heavy-trucks'), ('Diesel agricultural equipment', 'Diesel agricultural equipment'), ('Diesel ships and boats', 'Diesel ships and boats'), ('Diesel medium-and-heavy-duty-Vehicles', 'Diesel-medium-and-heavy-Vehicles'), ('Other diesel Non-Road Vehicles', 'Other diesel Non-Road Vehicles'), ('Gasoline passenger cars', 'Gasoline passenger cars'), ('Gasoline light-duty trucks', 'Gasoline light-duty'), ('Gasoline medium-and-heavy-trucks', 'Gasoline medium-and-heavy-trucks'), ('Gasoline agricultural equipment', 'Gasoline agricultural equipment'), ('Gasoline ships and boats', 'Gasoline ships and boats'), ('Gasoline medium-and-heavy-duty-Vehicles', 'Gasoline-medium-and-heavy-Vehicles'), ('Other gasoline Non-Road Vehicles', 'Other gasoline Non-Road Vehicles')], max_length=255)),
                ('measure_unit', models.CharField(default='L', max_length=30)),
                ('emission_factor', models.FloatField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerant',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')])),
                ('year', models.CharField(max_length=4)),
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('refrigerant_type', models.CharField(max_length=255)),
                ('refrigerant_quantity', models.FloatField(default=0.0, max_length=10)),
                ('emission_factor', models.FloatField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sf6',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')])),
                ('year', models.CharField(max_length=4)),
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('equipment_type', models.CharField(max_length=255)),
                ('equipment_producer', models.CharField(max_length=255)),
                ('sf6_quantity', models.FloatField(max_length=10)),
                ('emission_factor', models.FloatField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('base_year', models.IntegerField(blank=True, default=2019, null=True)),
                ('net_zero_year', models.IntegerField(blank=True, default=2050, null=True)),
                ('intermediate_year', models.IntegerField(blank=True, default=2020, null=True)),
                ('co2e_base_year', models.IntegerField(default=0)),
                ('reduction_percentage', models.FloatField(default=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')])),
                ('year', models.CharField(max_length=4)),
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('emission_factor', models.FloatField(default=0, null=True)),
                ('distance', models.FloatField()),
                ('fuel_consumption', models.FloatField(default=7.5)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')])),
                ('year', models.CharField(max_length=4)),
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('waste_name', models.CharField(max_length=255)),
                ('quantity_recycled', models.FloatField()),
                ('quantity_disposed', models.FloatField()),
                ('quantity_land_filled', models.FloatField()),
                ('emission_factor', models.FloatField(default=0, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
    ]
