# Generated by Django 5.0.1 on 2024-01-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopetwoemission',
            name='total_co2_scope_two',
        ),
    ]
