# Generated by Django 5.0.1 on 2024-06-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
