# Generated by Django 5.0.1 on 2024-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
