# Generated by Django 5.0.1 on 2024-03-21 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Natural gas', 'Natural gas'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Natural gas', 'Natural gas'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='refrigerant',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Natural gas', 'Natural gas'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sf6',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Natural gas', 'Natural gas'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='travel',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Natural gas', 'Natural gas'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='waste',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Natural gas', 'Natural gas'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.CreateModel(
            name='NaturalGas',
            fields=[
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')])),
                ('year', models.CharField(max_length=4)),
                ('emission_type', models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Natural gas', 'Natural gas'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255)),
                ('emission_scope', models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=255)),
                ('location', models.CharField(choices=[('Location 1', 'Location 1'), ('Location 2', 'Location 2'), ('Location 3', 'Location 3'), ('Location 4', 'Location 4'), ('Location 5', 'Location 5')], max_length=255)),
                ('gas_quantity', models.FloatField(default=0, max_length=10)),
                ('emission_factor', models.FloatField(default=0)),
                ('measure_unit', models.CharField(default='kWh', max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
    ]
