# Generated by Django 5.0.1 on 2024-03-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='energy_quantity',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='vehicle_type',
            field=models.CharField(choices=[('Diesel passenger cars', 'Diesel passenger cars'), ('Diesel light-duty trucks', 'Diesel light-duty'), ('Diesel medium-and-heavy-trucks', 'Diesel medium-and-heavy-trucks'), ('Diesel agricultural equipment', 'Diesel agricultural equipment'), ('Diesel ships and boats', 'Diesel ships and boats'), ('Diesel medium-and-heavy-duty-Vehicles', 'Diesel-medium-and-heavy-Vehicles'), ('Other diesel Non-Road Vehicles', 'Other diesel Non-Road Vehicles'), ('Gasoline passenger cars', 'Gasoline passenger cars'), ('Gasoline light-duty trucks', 'Gasoline light-duty'), ('Gasoline medium-and-heavy-trucks', 'Gasoline medium-and-heavy-trucks'), ('Gasoline agricultural equipment', 'Gasoline agricultural equipment'), ('Gasoline ships and boats', 'Gasoline ships and boats'), ('Gasoline medium-and-heavy-duty-Vehicles', 'Gasoline-medium-and-heavy-Vehicles'), ('Other gasoline Non-Road Vehicles', 'Other gasoline Non-Road Vehicles')], max_length=255),
        ),
    ]
