# Generated by Django 5.0.1 on 2024-05-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonomyturnover',
            old_name='activity',
            new_name='turnover_activity',
        ),
    ]
