# Generated by Django 5.0.1 on 2024-03-07 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('base_year', models.IntegerField(blank=True, default=2019, null=True)),
                ('net_zero_year', models.IntegerField(blank=True, default=2050, null=True)),
                ('co2e_base_year', models.IntegerField(default=0)),
                ('reduction_percentage', models.FloatField(default=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
    ]
