# Generated by Django 5.0.1 on 2024-01-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0002_remove_scopetwoemission_total_co2_scope_two'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScopeThreeEmission',
        ),
    ]
