# Generated by Django 5.0.1 on 2024-03-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0002_energy_energy_quantity_alter_fuel_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='refrigerant',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sf6',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='travel',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
        migrations.AlterField(
            model_name='waste',
            name='emission_type',
            field=models.CharField(choices=[('Car fuels', 'Car fuels'), ('SF6', 'SF6'), ('Refrigerants', 'Refrigerants'), ('Energy Acquisition', 'Energy Acquisition'), ('Travel', 'Travel'), ('Waste', 'Waste')], max_length=255),
        ),
    ]
