# Generated by Django 5.0.1 on 2024-06-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0002_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
