# Generated by Django 5.0.1 on 2024-03-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0002_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='intermediate_year',
            field=models.IntegerField(blank=True, default=2020, null=True),
        ),
    ]
