# Generated by Django 5.0.1 on 2024-05-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0002_taxonomysector_taxonomyopex_taxonomycapex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomyturnover',
            name='climate_change_adaptation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomyturnover',
            name='climate_change_mitigation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255),
        ),
    ]
