# Generated by Django 5.0.1 on 2024-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0003_target_intermediate_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='sf6',
            name='emission_factor',
            field=models.FloatField(default=0),
        ),
    ]
