# Generated by Django 5.0.1 on 2024-01-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0003_delete_scopethreeemission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyacquisition',
            name='emission_scope',
        ),
        migrations.RemoveField(
            model_name='refrigerantemission',
            name='emission_scope',
        ),
        migrations.RemoveField(
            model_name='fuelemission',
            name='emission_scope',
        ),
        migrations.RemoveField(
            model_name='sf6emission',
            name='emission_scope',
        ),
        migrations.RemoveField(
            model_name='scopetwoemission',
            name='emission_type',
        ),
        migrations.DeleteModel(
            name='ScopeOneEmission',
        ),
        migrations.DeleteModel(
            name='ScopeTwoEmission',
        ),
    ]
