# Generated by Django 5.0.1 on 2024-05-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0003_alter_taxonomyturnover_climate_change_adaptation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomycapex',
            name='climate_change_adaptation',
            field=models.FloatField(default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomycapex',
            name='climate_change_mitigation',
            field=models.FloatField(default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomyopex',
            name='climate_change_adaptation',
            field=models.FloatField(default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomyopex',
            name='climate_change_mitigation',
            field=models.FloatField(default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomyturnover',
            name='climate_change_adaptation',
            field=models.FloatField(default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name='taxonomyturnover',
            name='climate_change_mitigation',
            field=models.FloatField(default=0.0, max_length=255),
        ),
    ]
