# Generated by Django 5.0.1 on 2024-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0004_sf6_emission_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerant',
            name='emission_factor',
            field=models.FloatField(default=0),
        ),
    ]
