# Generated by Django 5.0.1 on 2024-05-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0004_alter_taxonomycapex_climate_change_adaptation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomysector',
            name='activity',
        ),
    ]
