# Generated by Django 5.0.1 on 2024-01-14 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0004_remove_energyacquisition_emission_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceCalculation',
            fields=[
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
