# Generated by Django 5.0.1 on 2024-05-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0005_remove_taxonomysector_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomysector',
            name='activity',
            field=models.CharField(choices=[('Transmission and distribution of electricity', 'Transmission and distribution of electricity')], default='activity_choice'),
        ),
    ]
