# Generated by Django 5.0.1 on 2024-03-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0005_refrigerant_emission_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='emission_factor',
            field=models.FloatField(default=0, null=True),
        ),
    ]
