# Generated by Django 5.0.1 on 2024-05-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0006_taxonomysector_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomysector',
            options={},
        ),
        migrations.RenameField(
            model_name='taxonomycapex',
            old_name='sector',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='taxonomyopex',
            old_name='sector',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='taxonomyturnover',
            old_name='sector',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='taxonomycapex',
            name='capex',
        ),
        migrations.RemoveField(
            model_name='taxonomycapex',
            name='capex_a_activity',
        ),
        migrations.RemoveField(
            model_name='taxonomycapex',
            name='capex_a_amount',
        ),
        migrations.RemoveField(
            model_name='taxonomycapex',
            name='capex_b_activity',
        ),
        migrations.RemoveField(
            model_name='taxonomycapex',
            name='capex_b_amount',
        ),
        migrations.RemoveField(
            model_name='taxonomycapex',
            name='capex_c_activity',
        ),
        migrations.RemoveField(
            model_name='taxonomycapex',
            name='capex_c_amount',
        ),
        migrations.RemoveField(
            model_name='taxonomycapex',
            name='climate_change_adaptation',
        ),
        migrations.RemoveField(
            model_name='taxonomycapex',
            name='climate_change_mitigation',
        ),
        migrations.RemoveField(
            model_name='taxonomyopex',
            name='climate_change_adaptation',
        ),
        migrations.RemoveField(
            model_name='taxonomyopex',
            name='climate_change_mitigation',
        ),
        migrations.RemoveField(
            model_name='taxonomyopex',
            name='opex',
        ),
        migrations.RemoveField(
            model_name='taxonomyopex',
            name='opex_a_activity',
        ),
        migrations.RemoveField(
            model_name='taxonomyopex',
            name='opex_a_amount',
        ),
        migrations.RemoveField(
            model_name='taxonomyopex',
            name='opex_b_activity',
        ),
        migrations.RemoveField(
            model_name='taxonomyopex',
            name='opex_b_amount',
        ),
        migrations.RemoveField(
            model_name='taxonomyopex',
            name='opex_c_activity',
        ),
        migrations.RemoveField(
            model_name='taxonomyopex',
            name='opex_c_amount',
        ),
        migrations.RemoveField(
            model_name='taxonomyturnover',
            name='aligned_activity',
        ),
        migrations.RemoveField(
            model_name='taxonomyturnover',
            name='aligned_activity_amount',
        ),
        migrations.RemoveField(
            model_name='taxonomyturnover',
            name='climate_change_adaptation',
        ),
        migrations.RemoveField(
            model_name='taxonomyturnover',
            name='climate_change_mitigation',
        ),
        migrations.RemoveField(
            model_name='taxonomyturnover',
            name='eligible_activity',
        ),
        migrations.RemoveField(
            model_name='taxonomyturnover',
            name='eligible_activity_amount',
        ),
        migrations.RemoveField(
            model_name='taxonomyturnover',
            name='not_aligned_activity',
        ),
        migrations.RemoveField(
            model_name='taxonomyturnover',
            name='not_aligned_activity_amount',
        ),
        migrations.RemoveField(
            model_name='taxonomyturnover',
            name='turnover',
        ),
        migrations.AddField(
            model_name='taxonomycapex',
            name='biodiversity_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomycapex',
            name='capex_aligned',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomycapex',
            name='capex_eligible',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomycapex',
            name='capex_non_aligned',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomycapex',
            name='circular_economy_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomycapex',
            name='climate_change_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomycapex',
            name='marine_resources_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomycapex',
            name='pollution_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomycapex',
            name='total_capex',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyopex',
            name='biodiversity_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyopex',
            name='circular_economy_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyopex',
            name='climate_change_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyopex',
            name='marine_resources_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyopex',
            name='opex_aligned',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyopex',
            name='opex_eligible',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyopex',
            name='opex_non_aligned',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyopex',
            name='pollution_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyopex',
            name='total_opex',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomysector',
            name='type',
            field=models.CharField(choices=[('Eligible', 'Eligible'), ('Aligned', 'Aligned'), ('Not Aligned', 'Not Aligned')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyturnover',
            name='biodiversity_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyturnover',
            name='circular_economy_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyturnover',
            name='climate_change_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyturnover',
            name='marine_resources_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyturnover',
            name='pollution_dnsh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='selection', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyturnover',
            name='total_turnover',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyturnover',
            name='turnover_aligned',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyturnover',
            name='turnover_eligible',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyturnover',
            name='turnover_non_aligned',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomysector',
            name='activity',
            field=models.CharField(choices=[('Transmission and distribution of electricity', 'Transmission and distribution of electricity')]),
        ),
        migrations.DeleteModel(
            name='DoNotSeriousHarm',
        ),
    ]
