# Generated by Django 5.0.1 on 2024-01-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0006_wastecalculation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistanceCalculation',
            new_name='Travel',
        ),
    ]
