# Generated by Django 5.0.1 on 2024-04-14 16:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envdata', '0003_alter_target_intermediate_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetZeroBusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ESGActionPlan',
            fields=[
                ('plan_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='ESGPillars',
            fields=[
                ('pillar', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
        ),
        migrations.CreateModel(
            name='ESGActionPlanObjectives',
            fields=[
                ('objective', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('responsible', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('completion', models.FloatField(default=0, help_text='Percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgmanager.esgactionplan')),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgmanager.esgpillars')),
            ],
        ),
        migrations.CreateModel(
            name='ESGActionPlanActions',
            fields=[
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('responsible', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('completion', models.FloatField(default=0, help_text='Percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgmanager.esgactionplan')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgmanager.esgactionplanobjectives')),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgmanager.esgpillars')),
            ],
        ),
        migrations.AddField(
            model_name='esgactionplan',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esgmanager.esgpillars'),
        ),
    ]
