# Generated by Django 5.0.1 on 2024-04-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgactionplanactions',
            name='completion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='esgactionplanobjectives',
            name='completion',
            field=models.FloatField(default=0),
        ),
    ]
