# Generated by Django 5.0.1 on 2024-05-09 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0003_alter_target_intermediate_year'),
        ('esgmanager', '0002_alter_esgactionplanactions_completion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateChangeRisk',
            fields=[
                ('category', models.CharField(choices=[('Sea-Level Rise', 'Sea-Level Rise'), ('Extreme Weather', 'Extreme Weather'), ('Temperature Increase', 'Temperature Increase'), ('Drought', 'Drought'), ('Flooding', 'Flooding'), ('Wildfires', 'Wildfires'), ('Glacial Melting', 'Glacial Melting'), ('Ocean Acidification', 'Ocean Acidification'), ('Biodiversity Loss', 'Biodiversity Loss'), ('Climate Migration', 'Climate Migration'), ('Food Security', 'Food Security'), ('Water Scarcity', 'Water Scarcity'), ('Heatwaves', 'Heatwaves'), ('Ecosystem Disruption', 'Ecosystem Disruption')], default='category', max_length=255)),
                ('risk', models.CharField(max_length=255)),
                ('description', models.TextField(default='description')),
                ('probability', models.PositiveSmallIntegerField(default=1, help_text='Scale from 1 (Low) to 10 (High)')),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='Scale from 1 (Low) to 10 (High)')),
                ('mitigation_measures', models.TextField(default='mitigation measure')),
                ('opportunities', models.TextField(blank=True, default='opportunities', null=True)),
                ('responsible', models.CharField(default='responsible', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
            options={
                'verbose_name': 'Climate Change Risk',
                'verbose_name_plural': 'Climate Change Risks',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalRisk',
            fields=[
                ('category', models.CharField(choices=[('Climate Change', 'Climate Change'), ('Air Pollution', 'Air Pollution'), ('Water Pollution', 'Water Pollution'), ('Soil Degradation', 'Soil Degradation'), ('Deforestation', 'Deforestation'), ('Biodiversity Loss', 'Biodiversity Loss'), ('Ocean Acidification', 'Ocean Acidification'), ('Overfishing', 'Overfishing'), ('Plastic Pollution', 'Plastic Pollution'), ('Chemical Spills', 'Chemical Spills'), ('Pesticide Use', 'Pesticide Use'), ('Waste Management', 'Waste Management'), ('Nuclear Accidents', 'Nuclear Accidents'), ('Land Use Changes', 'Land Use Changes'), ('Desertification', 'Desertification'), ('Noise Pollution', 'Noise Pollution'), ('Light Pollution', 'Light Pollution'), ('Endocrine Disruptors', 'Endocrine Disruptors'), ('E-waste', 'E-waste'), ('Invasive Species', 'Invasive Species')], default='category', max_length=255)),
                ('risk', models.CharField(max_length=255)),
                ('description', models.TextField(default='description')),
                ('probability', models.PositiveSmallIntegerField(default=1, help_text='Scale from 1 (Low) to 10 (High)')),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='Scale from 1 (Low) to 10 (High)')),
                ('mitigation_measures', models.TextField(default='mitigation measure')),
                ('opportunities', models.TextField(blank=True, default='opportunities', null=True)),
                ('responsible', models.CharField(default='responsible', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
            options={
                'verbose_name': 'Environmental Risk',
                'verbose_name_plural': 'Environmental Risks',
            },
        ),
        migrations.CreateModel(
            name='GovernanceRisks',
            fields=[
                ('category', models.CharField(choices=[('Regulatory Compliance', 'Regulatory Compliance'), ('Corruption', 'Corruption'), ('Board Composition', 'Board Composition'), ('Executive Compensation', 'Executive Compensation'), ('Bribery', 'Bribery'), ('Tax Avoidance', 'Tax Avoidance'), ('Data Privacy', 'Data Privacy'), ('Whistleblower Protection', 'Whistleblower Protection'), ('Corporate Governance', 'Corporate Governance'), ('Supply Chain Ethics', 'Supply Chain Ethics'), ('Lobbying and Political Influence', 'Lobbying and Political Influence'), ('Transparency', 'Transparency'), ('Conflicts of Interest', 'Conflicts of Interest'), ('Internal Controls', 'Internal Controls')], default='category', max_length=255)),
                ('risk', models.CharField(max_length=255)),
                ('description', models.TextField(default='description')),
                ('probability', models.PositiveSmallIntegerField(default=1, help_text='Scale from 1 (Low) to 10 (High)')),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='Scale from 1 (Low) to 10 (High)')),
                ('mitigation_measures', models.TextField(default='mitigation measure')),
                ('opportunities', models.TextField(blank=True, default='opportunities', null=True)),
                ('responsible', models.CharField(default='responsible', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
            options={
                'verbose_name': 'Governance Risk',
                'verbose_name_plural': 'Governance Risks',
            },
        ),
        migrations.CreateModel(
            name='SocialRisk',
            fields=[
                ('category', models.CharField(choices=[('Political Instability', 'Political Instability'), ('Unemployment', 'Unemployment'), ('Income Inequality', 'Income Inequality'), ('Discrimination', 'Discrimination'), ('Health Epidemics', 'Health Epidemics'), ('Labor Rights Violations', 'Labor Rights Violations'), ('Access to Education', 'Access to Education'), ('Crime and Violence', 'Crime and Violence'), ('Corruption', 'Corruption'), ('Human Rights Violations', 'Human Rights Violations'), ('Forced Migration', 'Forced Migration'), ('Aging Population', 'Aging Population'), ('Social Unrest', 'Social Unrest'), ('Food Security', 'Food Security'), ('Housing Crisis', 'Housing Crisis')], default='category', max_length=255)),
                ('risk', models.CharField(max_length=255)),
                ('description', models.TextField(default='description')),
                ('probability', models.PositiveSmallIntegerField(default=1, help_text='Scale from 1 (Low) to 10 (High)')),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='Scale from 1 (Low) to 10 (High)')),
                ('mitigation_measures', models.TextField(default='mitigation measure')),
                ('opportunities', models.TextField(blank=True, default='opportunities', null=True)),
                ('responsible', models.CharField(default='responsible', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdata.company')),
            ],
            options={
                'verbose_name': 'Social Risk',
                'verbose_name_plural': 'Social Risks',
            },
        ),
    ]
